sudo: required

language: C

services:
- docker

env:
  global:
      - MOUNT_DIR=/root/nanvix/hal
      - SSH_KEY=tools/ssh/travis_rsa.enc
      - SSH_CONFIG=tools/ssh/config
      - SERVER_NAME=mppa

jobs:
  include:
    # Build Debug
    - stage: "Build Debug"
      name: "QEMU OpenRISC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-openrisc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && make distclean  && make all"
    - stage: "Build Debug"
      name: "QEMU x86"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-i486 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-x86 && export TOOLCHAIN_DIR=/root/toolchain/i486/bin && make distclean && make all"
    - stage: "Build Debug"
      name: "QEMU RISC-V 32-Bit"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-riscv32 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-riscv32 && export TOOLCHAIN_DIR=/root/toolchain/riscv32/bin && make distclean && make all"
    - stage: "Build Debug"
      name: "MPPA-256"
      if: (NOT type IN (pull_request))
      before_script:
        - openssl aes-256-cbc -K $encrypted_b4131d7a7a41_key -iv $encrypted_b4131d7a7a41_iv -in $SSH_KEY -out travis_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 travis_rsa
        - cp $SSH_CONFIG ~/.ssh/config
        - ssh-add travis_rsa
      script:
        - rsync -avz --delete-after --exclude=".git" . $SERVER_NAME:~/travis/hal
        - ssh $SERVER_NAME 'bash travis/build-hal.sh --no-verbose --debug'

    # Build Release
    - stage: "Build Release"
      name: "QEMU OpenRISC"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-openrisc /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-openrisc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && export RELEASE=true && make distclean  && make all"
    - stage: "Build Release"
      name: "QEMU x86"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-i486 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-x86 && export TOOLCHAIN_DIR=/root/toolchain/i486/bin && export RELEASE=true && make distclean && make all"
    - stage: "Build Release"
      name: "QEMU RISC-V 32-Bit"
      script: docker run -v"$(pwd):$MOUNTDIR/hal" -p4567:4567 nanvix/toolchain-riscv32 /bin/sh -c "cd $MOUNTDIR/hal && export TARGET=qemu-riscv32 && export TOOLCHAIN_DIR=/root/toolchain/riscv32/bin && export RELEASE=true && make distclean && make all"
    - stage: "Build Release"
      name: "MPPA-256"
      if: (NOT type IN (pull_request))
      before_script:
        - openssl aes-256-cbc -K $encrypted_b4131d7a7a41_key -iv $encrypted_b4131d7a7a41_iv -in $SSH_KEY -out travis_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 travis_rsa
        - cp $SSH_CONFIG ~/.ssh/config
        - ssh-add travis_rsa
      script:
        - rsync -avz --delete-after --exclude=".git" . $SERVER_NAME:~/travis/hal
        - ssh $SERVER_NAME 'bash travis/build-hal.sh --no-verbose --release'

notifications:
  slack: nanvix:31ePVjsrXynUajPUDqy6I0hp
