sudo: required

language: C

services:
- docker

script:
- docker run -v"$(pwd):/root/nanvix/hal" -p4567:4567 nanvix/toolchain-openrisc:latest /bin/sh -c "cd /root/nanvix/hal && export TARGET=or1k-pc && export TOOLCHAIN_DIR=/root/toolchain/or1k/bin && make distclean  && make all"
- find src/ -name *.o -exec rm -rf {} \;
- find src/ -name *.a -exec rm -rf {} \;
- docker run -v"$(pwd):/root/nanvix/hal" -p4567:4567 nanvix/toolchain-x86:latest /bin/sh -c "cd /root/nanvix/hal && export TARGET=i386-pc && export TOOLCHAIN_DIR=/root/toolchain/i386/bin && make distclean && make all"

